logging:
  file:
    path: /Users/kyokuryou/tmp/logs/${spring.application.name}
  logstash:
    name: ${spring.application.name}
    version: 1
    domains: 192.168.37.189:4560,192.168.37.189:4560
  pattern:
    console: '%-5p %c{1} - %m%n'
    file: '%d [%7r] %6p - %30.30c - %m%n'
    logstash: '%d [%7r] %6p - %30.30c - %m%n'
spring:
  application:
    name: jerry-test
  profiles:
    active: '@profileActive@'
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    basename: i18n/jerry,i18n/resource
    encoding: UTF-8
    cache-duration: 60
  session:
    store-type: jdbc

jerry:
  context:
    storage-client:
      store-type: CRYPTO
      directory: /tmp1
      hostname: 127.0.0.1
      port: 8881
    storage-server:
      enabled: false
      store-type: CRYPTO
      directory: /Users/kyokuryou/tmp/
      port: 8881

---
#############################
###  dev profile
#############################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
  freemarker:
    cache: false
  redis:
    host: localhost
    password: 123456
jerry:
  shiro:
    single-session: false

---
#############################
###  prod profile
#############################
spring:
  profiles: prod
  datasource:
    url: jdbcTemplate:mysql://localhost/test1111
    username: dbuser
    password: dbpass