logging:
  path: /Users/kyokuryou/tmp/logs/${spring.application.name}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger - %msg%n'
spring:
  application:
    name: jerry-test
  boot:
    enableautoconfiguration: false
  profiles:
    active: '@profileActive@'
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    basename: i18n/jerry,i18n/resource
    encoding: UTF-8
    cache-seconds: 3600
  session:
    store-type: jdbc

jerry:
  context:
    finder:
      directory: /Users/kyokuryou/tmp/upload
    storage-client:
      store-type: CRYPTO
      directory: /tmp1
      hostname: 127.0.0.1
      port: 8881
    storage-server:
      enabled: true
      store-type: CRYPTO
      directory: D:\tmp
      port: 8881

---
#############################
###  dev profile
#############################
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: 123456
  freemarker:
    cache: false
jerry:
  shiro:
    single-session: false

---
#############################
###  prod profile
#############################
spring:
  profiles: prod
  datasource:
    url: jdbcTemplate:mysql://localhost/test1111
    username: dbuser
    password: dbpass